# Generated by Django 5.1.2 on 2024-12-05 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'запись', 'verbose_name_plural': 'записи'},
        ),
    ]
